// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password, name FROM admins WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password, name FROM admins WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
	)
	return i, err
}
