// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Admin struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
	Name     string    `json:"name"`
}

type User struct {
	ID               uuid.UUID      `json:"id"`
	Email            string         `json:"email"`
	Password         string         `json:"password"`
	Name             string         `json:"name"`
	Surname          string         `json:"surname"`
	Phone            sql.NullString `json:"phone"`
	Role             string         `json:"role"`
	ImageProfile     sql.NullString `json:"image_profile"`
	StripeCustomerID sql.NullString `json:"stripe_customer_id"`
	IsActive         bool           `json:"is_active"`
	LastLogin        sql.NullTime   `json:"last_login"`
	CreatedAt        time.Time      `json:"created_at"`
}
